import { NextResponse } from "next/server";
import { HORIZON_DAYS } from "@/lib/ai/apply";

export const dynamic = "force-dynamic";

/**
 * The interface, described by itself.
 *
 * A model that fetches this once can drive the whole app without external
 * documentation, and errors elsewhere point back here. Written as prose plus
 * examples rather than raw JSON Schema, because that is what models follow
 * most reliably.
 */
export async function GET() {
  return NextResponse.json({
    name: "Discipline",
    what: "A day planner where a scheduled block can enforce itself: it rings at its start time and will not stop until a challenge is solved.",

    conventions: {
      time: 'Local wall-clock only. Dates are "YYYY-MM-DD", times are 24-hour "HH:MM", spans are "16:00-18:00". Never send ISO or UTC.',
      naming: 'Address categories and subcategories by name. They are created on demand, so never look up an id first.',
      keys: 'Give an op a "key" to make it re-appliable. Sending the same plan again edits what that key made instead of duplicating it.',
      recurrence:
        'Nothing repeats unless you pass "repeat". A block without it exists on its given date(s) only.',
      scope:
        'update and delete default to the matched occurrences only and never rewrite a rule. If your selector hits blocks generated by a rule and you did not set "scope", the call is refused with needsScope and nothing is written — relay that question to the user rather than guessing.',
    },

    endpoints: {
      "GET /api/ai/context":
        "Everything in one call: today, categories, blocks in a window, rules, goals, inbox. Params: from, days (default 14), analytics=1.",
      "GET /api/ai/query": "Discipline and time-use summary. Param: preset=WEEK|MONTH|HALF_YEAR|YEAR.",
      "POST /api/ai/apply": "All writing. Body: { ops: [...], dryRun?: boolean }.",
      "GET /api/ai/describe": "This document.",
    },

    auth: 'Authorization: Bearer <token>. Create one in Settings → Agent access.',

    ops: {
      schedule: {
        what: "Add blocks. One-off unless `repeat` is given.",
        fields: {
          title: "Shown on the block.",
          category: "Name. Created if new.",
          sub: "Optional subcategory name.",
          time: '"16:00-18:00". An end before the start means it runs past midnight.',
          date: 'Single day, or use "dates": ["2026-09-07", ...].',
          repeat: '{ weekdays: ["MON","WED"], from?: "YYYY-MM-DD", until?: "YYYY-MM-DD" } — ONLY when a real rule is wanted.',
          note: "Free text; also what a VOICE alarm says by default.",
          priority: "STANDARD | MEDIUM | MAX",
          enforce:
            '{ mode, challenge, difficulty, streak, say?, vibrate? } or omit for an ordinary block.',
          key: "Stable handle for later selectors and re-application.",
        },
      },
      update: {
        what: "Change every block matching a selector.",
        fields: {
          where: "Selector, see below.",
          set: "{ time?, note?, priority?, category?, sub?, enforce?, completed?, countInStats? }. enforce: null turns enforcement off.",
          scope: "this | future | all. Required only when the selection includes rule-generated blocks.",
        },
      },
      delete: {
        what: "Remove matching blocks. Deleted occurrences of a rule are tombstoned so they are not regenerated. scope future/all also stops the rule.",
        fields: { where: "Selector.", scope: "this | future | all." },
      },
      goal: {
        what: "Create or update a target, matched by title.",
        fields: {
          title: "Required.",
          metric: "DURATION | TASK_COUNT",
          direction: "AT_LEAST | AT_MOST",
          target: 'For DURATION: "10h", "90m", "1h30m". For TASK_COUNT: a number.',
          scope: "{ category?, sub? }; omit for everything.",
          until: '"YYYY-MM-DD".',
        },
      },
    },

    selector: {
      key: "Blocks created under this plan key.",
      category: "Category name.",
      sub: "Subcategory name.",
      note: "Substring of the note.",
      from: "Inclusive start date.",
      to: "Inclusive end date.",
      weekdays: '["MON","TUE",...] — this is how you address "the Friday ones".',
      nth: 'odd | even over the matched set, in time order — this is how you address "half of them".',
      enforced: "true or false.",
      ids: "Explicit block ids, as an escape hatch.",
    },

    enums: {
      wakeMode: {
        SILENT: "One notification, then nothing. A nudge that does not nag.",
        VIBRATE: "Notifications repeat about once a second, so the phone buzzes continuously. No sound.",
        SIREN: "Repeats, plus a loud two-tone alarm while the app is open.",
        VOICE: "Repeats, plus the block spoken aloud while the app is open.",
      },
      challenge: ["math", "typing"],
      difficulty: ["easy", "medium", "hard"],
      streak: [1, 3, 5],
      priority: ["STANDARD", "MEDIUM", "MAX"],
      weekdays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"],
    },

    limits: {
      opsPerPlan: 100,
      horizonDays: HORIZON_DAYS,
      horizonNote: `Rules are materialised ${HORIZON_DAYS} days ahead on a rolling basis and topped up daily, so "until" may be far beyond what context returns.`,
    },

    example: {
      comment:
        "A term of classes, Fridays softened, and a weekly target — one call, where the old REST API needed about forty-six.",
      body: {
        ops: [
          {
            op: "schedule",
            key: "physics",
            title: "Physics",
            category: "Study",
            sub: "Physics",
            time: "16:00-18:00",
            repeat: { weekdays: ["MONDAY", "WEDNESDAY", "FRIDAY"], until: "2026-12-15" },
            note: "Mechanics — problem sets",
            enforce: { mode: "SIREN", challenge: "math", difficulty: "medium", streak: 3 },
          },
          {
            op: "update",
            where: { key: "physics", weekdays: ["FRIDAY"] },
            scope: "future",
            set: { enforce: { mode: "VIBRATE" }, note: "Physics — revision only" },
          },
          {
            op: "goal",
            title: "Study 10h a week",
            scope: { category: "Study" },
            metric: "DURATION",
            direction: "AT_LEAST",
            target: "10h",
            until: "2026-12-15",
          },
        ],
      },
    },
  });
}
